// Auto-generated by drizzle-kit. Run `npm run db:generate` to regenerate after schema changes.
export default {
  journal: {
    version: "7",
    dialect: "sqlite",
    entries: [] as Array<{ idx: number; version: string; when: number; tag: string; breakpoints: boolean }>
  },
  migrations: {} as Record<string, string>
};
